//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVuPhuTung
    {
        public string MaPT { get; set; }
        public string Ten { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> TonKho { get; set; }
        public string Loai { get; set; }
    }
}
