//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string MaNV { get; set; }
        public string MaKH { get; set; }
        public string TenDV_SP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public string TrangThai { get; set; }

        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
