//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        public string MaXe { get; set; }
        public string TenXe { get; set; }
        public string LoaiXe { get; set; }
        public Nullable<int> NamSX { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string MauSac { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public string MaHang { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        public virtual HangXe HangXe { get; set; }
    }
}
