//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDH
    {
        public System.Guid MaDH { get; set; }
        public int MaXe { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
