//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.ChiTietDHs = new HashSet<ChiTietDH>();
            this.KhoXes = new HashSet<KhoXe>();
        }
    
        public int Id { get; set; }
        public string TenHang { get; set; }
        public string TenDongXe { get; set; }
        public string LoaiXe { get; set; }
        public string MauSac { get; set; }
        public Nullable<int> NamSX { get; set; }
        public Nullable<long> GiaXe { get; set; }
        public string HinhAnhFullPath { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        public virtual HangXe HangXe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDH> ChiTietDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoXe> KhoXes { get; set; }
    }
}
