//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DL_OTOEntities2 : DbContext
    {
        public DL_OTOEntities2()
            : base("name=DL_OTOEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<ChiTietDH> ChiTietDHs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<HangXe> HangXes { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KhoXe> KhoXes { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThanhToan> ThanhToans { get; set; }
        public virtual DbSet<vw_DanhSachNhanVien> vw_DanhSachNhanVien { get; set; }
        public virtual DbSet<vw_TonKho> vw_TonKho { get; set; }
        public virtual DbSet<vw_XeBanChay> vw_XeBanChay { get; set; }
    
        public virtual int sp_SuaKhachHang(string soDienThoai, string hoTen, string gioiTinh, Nullable<System.DateTime> ngaySinh, string email)
        {
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaKhachHang", soDienThoaiParameter, hoTenParameter, gioiTinhParameter, ngaySinhParameter, emailParameter);
        }
    
        public virtual int sp_ThanhToan(Nullable<System.Guid> maDH, string phuongThuc)
        {
            var maDHParameter = maDH.HasValue ?
                new ObjectParameter("MaDH", maDH) :
                new ObjectParameter("MaDH", typeof(System.Guid));
    
            var phuongThucParameter = phuongThuc != null ?
                new ObjectParameter("PhuongThuc", phuongThuc) :
                new ObjectParameter("PhuongThuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThanhToan", maDHParameter, phuongThucParameter);
        }
    
        public virtual int sp_ThemKhachHang(string hoTen, string gioiTinh, string soDienThoai, Nullable<System.DateTime> ngaySinh, string email)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemKhachHang", hoTenParameter, gioiTinhParameter, soDienThoaiParameter, ngaySinhParameter, emailParameter);
        }
    
        public virtual int sp_ThemNhanVien(string hoTen, Nullable<System.DateTime> ngaySinh, string gioiTinh, string chucVu, Nullable<decimal> luong)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", hoTenParameter, ngaySinhParameter, gioiTinhParameter, chucVuParameter, luongParameter);
        }
    
        public virtual int sp_ThongKeDoanhThu_Cursor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThongKeDoanhThu_Cursor");
        }
    
        public virtual int sp_XoaKhachHangMKH(Nullable<System.Guid> maKhachHang)
        {
            var maKhachHangParameter = maKhachHang.HasValue ?
                new ObjectParameter("MaKhachHang", maKhachHang) :
                new ObjectParameter("MaKhachHang", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaKhachHangMKH", maKhachHangParameter);
        }
    
        public virtual int sp_XoaKhachHangSDT(string soDienThoai)
        {
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaKhachHangSDT", soDienThoaiParameter);
        }
    
        public virtual int TaoDonHang(string tenDH, Nullable<System.Guid> maKhachHang, Nullable<int> maNV, Nullable<System.DateTime> ngayLap)
        {
            var tenDHParameter = tenDH != null ?
                new ObjectParameter("TenDH", tenDH) :
                new ObjectParameter("TenDH", typeof(string));
    
            var maKhachHangParameter = maKhachHang.HasValue ?
                new ObjectParameter("MaKhachHang", maKhachHang) :
                new ObjectParameter("MaKhachHang", typeof(System.Guid));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TaoDonHang", tenDHParameter, maKhachHangParameter, maNVParameter, ngayLapParameter);
        }
    }
}
