//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoXe
    {
        public int MaGiaoDich { get; set; }
        public int MaXe { get; set; }
        public string LoaiGiaoDich { get; set; }
        public int SoLuong { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
