//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public System.Guid MaTT { get; set; }
        public System.Guid MaDH { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public long SoTien { get; set; }
        public string PhuongThuc { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
