//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TonKho
    {
        public int MaXe { get; set; }
        public string TenHang { get; set; }
        public string TenDongXe { get; set; }
        public string LoaiXe { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    }
}
